name: rvm macOS 15 intel
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  macos15:
    name: macOS 15 (intel)
    runs-on: macos-15-intel
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - name: Install RVM
        run: |
          gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
          curl -sSL https://get.rvm.io | bash -s stable
      - name: Apply patch
        run: |
          mkdir -p ~/.rvm/patches/ruby/3.0.5
          curl --retry 5 --retry-delay 5 --location -o ~/.rvm/patches/ruby/3.0.5/fix-ftbfs-with-maybe-unused.patch https://github.com/ruby/ruby/commit/1dfe75b0beb7171b8154ff0856d5149be0207724.patch
          find ~/.rvm/patches/ruby/3.0.5
      # https://github.com/rvm/rvm/issues/5511
      - name: Install Ruby 3.0.5
        run: |
          source ~/.rvm/scripts/rvm
          rvm install 3.0.5 --patch ~/.rvm/patches/ruby/3.0.5/fix-ftbfs-with-maybe-unused.patch
      - name: Show make.log
        if: ${{ failure() }}
        run: |
          find ~/.rvm/log -name 'make.log' | xargs cat
      - name: Try install Ruby 3.0.5
        run: |
          source ~/.rvm/scripts/rvm
          rvm uninstall 3.0.5
          rvm cleanup all
          rvm try_install 3.0.5 --patch ~/.rvm/patches/ruby/3.0.5/fix-ftbfs-with-maybe-unused.patch
      - name: Show make.log
        if: ${{ failure() }}
        run: |
          find ~/.rvm/log -name 'make.log' | xargs cat
