name: rvm macOS 15 intel
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  macos15:
    name: macOS 15 (intel)
    runs-on: macos-15-intel
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - name: Install RVM
        run: |
          gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
          curl -sSL https://get.rvm.io | bash -s stable
      - name: Install Ruby 3.0.5
        run: |
          source ~/.rvm/scripts/rvm
          rvm install 3.0.5
